version: 2

project_name: sship

before:
  hooks:
    - go mod tidy

builds:
  - id: sship
    main: ./cmd/web
    binary: sship
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Windows ARM64는 제외 (수요가 적음)
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: sship
    name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
  groups:
    - title: 'Features'
      regexp: '^feat'
    - title: 'Bug Fixes'
      regexp: '^fix'
    - title: 'Performance'
      regexp: '^perf'

release:
  github:
    owner: lambda0x63
    name: sship
  name_template: "v{{.Version}}"
  header: |
    ## sship {{.Version}}
    
    SSH-based Docker Compose deployment tool with Web UI
  footer: |
    ## Installation

    ### Homebrew
    ```bash
    brew tap lambda0x63/tap
    brew install sship
    ```

    ### Direct Download
    Download the appropriate archive for your platform from the assets below.

homebrew_casks:
  - repository:
      owner: lambda0x63
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    
    homepage: "https://github.com/lambda0x63/sship"
    description: "SSH-based Docker Compose deployment tool with Web UI"
    license: "MIT"

